title: Mahamed Abdullahi
tagline: CS Student — Cybersecurity & Systems Programming

theme: jekyll-theme-cayman
show_downloads: false

author:
  name: Mahamed Abdullahi
  email: Mahamed518279@gmail.com

github_username: Mahamed88
